### ISSUE TITLE
VERY-BIG-SPIKE- search by genre and streaming service

### ISSUE THREAD

**Issue by Fallen-Master** [dan-watkins/movie-wishlist-builder#42]
Research API's for possibilities.
Rapid API might be able to do it...

**Comment by dan-watkins** [comment]
To implement we first need to call the "Genres" endpoint to get a list of ID's for each genre name.
We'd then need to create items in the drop down menu for each result and store the ID's as a reference.
With those ID's we call the "Search Basic" endpoint with that ID to get results back, and generate a movie card for each movie in the response.
